export type UserProfile = {
  userId: string;
  personId: string;
  empId: string;
  gender: string;
  firstNameEn: string;
  lastNameEN: string;
  firstName: string;
  lastName: string;
  preferredNameEn: string;
  userName: string;
  email: string;
  hiredDate: string;
  resignDate: string;
  positionCode: string;
  jobTitle: any;
  managerID: string;
  companyCode: string;
  businessUnitCode: string;
  functionCode: string;
  subFunction1Code: string;
  subFunction2Code: string;
  subFunction3Code: string;
  subFunction4Code: string;
  subFunction5Code: string;
  subFunction6Code: string;
  subFunction7Code: string;
  workingLocation: string;
  country: string;
  officePhone: string;
  ipPhone: string;
  status: boolean;
  dateOfBirth: string;
  costCenter: string;
  jobLevel: string;
  multipleJob: string;
  jobLevelDoa: string;
  userType: string;
  empIdOld: string;
  jobLevelModel: JobLevel;
  manager: any;
  nbtFirstName?: string;
  nbtSurname?: string;
  nbtId?: number;
  nbtPhoneNumber?: number;
  nbtEmail?: string;
  jobLevelName?: string;
  LanguageCode?: string;
};

export type JobLevel = {
  code: string;
  name: string;
  status: boolean;
};
